#!/bin/bash
set -euo pipefail

timestamp() {
	/usr/bin/date -Ins -u
}

say() {
	echo -e "$(timestamp): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

xml_escape() {
	local V="${1}"
	V="${V//&/&amp;}"
	V="${V//</&lt;}"
	V="${V//>/&gt;}"
	V="${V//\"/&quot;}"
	V="${V//\'/&apos;}"
	echo -n "${V}"
}

url_escape() {
	local V="${1}"
	echo -n "${V}" | /usr/bin/jq -sRr @uri
}

sed_escape() {
	local V="${1}"
	echo -n "${V}" | /usr/bin/sed -e 's;&;\\&;g'
}

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v CONF_DIR ] || CONF_DIR="${BASE_DIR}/conf"
[ -v DATA_DIR ] || DATA_DIR="${BASE_DIR}/data"
[ -v LOGS_DIR ] || LOGS_DIR="${BASE_DIR}/logs"

# Fork into the application
[ -v JAVA_MEM_ARGS ] || JAVA_ARGS="-XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0"
export JAVA_MEM_ARGS

# Update the SSL stuff
[ -v SSL_DIR ] || SSL_DIR="/.ssl"

# This is done because we can't risk having "weird" characters in the password
# b/c we can't find docs on how to escape said weird characters so they won't
# trip up netty's URL parsing. Using this model ensures our password will only
# contain alphanumeric characters (letters in both cases, and numbers)
acme-init

MAX_BOOT_DELAY="60"
if [ -v BOOT_DELAY ] && [[ "${BOOT_DELAY}" =~ ^[0-9]+$ ]] ; then
	BOOT_DELAY="$(( 10#${BOOT_DELAY} ))"
	if [ ${BOOT_DELAY} -gt 0 ] ; then
		[ ${BOOT_DELAY} -gt ${MAX_BOOT_DELAY} ] && BOOT_DELAY=${MAX_BOOT_DELAY}
		say "Applying a boot delay of ${BOOT_DELAY} seconds"
		START="$(date +%s)"
		while true ; do
			DIFF="$(( $(date +%s) - START ))"
			[ ${DIFF} -ge ${BOOT_DELAY} ] && break
			sleep 1 || fail "Boot delay aborted - exiting"
		done
	fi
fi

[ -e "${CONF_DIR}" ] || fail "The data directory [${CONF_DIR}] does not exist"
[ -d "${CONF_DIR}" ] || fail "The path [${CONF_DIR}] is not a directory"
[ -r "${CONF_DIR}" ] || fail "The data directory [${CONF_DIR}] is not readable by ${USER} (${UID}:$(id -g))"
[ -w "${CONF_DIR}" ] || fail "The data directory [${CONF_DIR}] is not writable by ${USER} (${UID}:$(id -g))"
[ -x "${CONF_DIR}" ] || fail "The data directory [${CONF_DIR}] is not executable by ${USER} (${UID}:$(id -g))"

[ -e "${DATA_DIR}" ] || fail "The data directory [${DATA_DIR}] does not exist"
[ -d "${DATA_DIR}" ] || fail "The path [${DATA_DIR}] is not a directory"
[ -r "${DATA_DIR}" ] || fail "The data directory [${DATA_DIR}] is not readable by ${USER} (${UID}:$(id -g))"
[ -w "${DATA_DIR}" ] || fail "The data directory [${DATA_DIR}] is not writable by ${USER} (${UID}:$(id -g))"
[ -x "${DATA_DIR}" ] || fail "The data directory [${DATA_DIR}] is not executable by ${USER} (${UID}:$(id -g))"

[ -e "${LOGS_DIR}" ] || fail "The data directory [${LOGS_DIR}] does not exist"
[ -d "${LOGS_DIR}" ] || fail "The path [${LOGS_DIR}] is not a directory"
[ -r "${LOGS_DIR}" ] || fail "The data directory [${LOGS_DIR}] is not readable by ${USER} (${UID}:$(id -g))"
[ -w "${LOGS_DIR}" ] || fail "The data directory [${LOGS_DIR}] is not writable by ${USER} (${UID}:$(id -g))"
[ -x "${LOGS_DIR}" ] || fail "The data directory [${LOGS_DIR}] is not executable by ${USER} (${UID}:$(id -g))"

export POD_HOSTNAME="$(hostname)"

if [ ! -v NODE_ID ] ; then
	say "No NODE_ID envvar was given, will attempt to guess it"
	if [ ! -v POD_NAME ] ; then
		say "No POD_NAME variable was found, will use the first component of the hostname instead"
		POD_NAME="${POD_HOSTNAME%%.*}"
	fi
	[[ "${POD_NAME}" =~ ^.*-([0-9]+)$ ]] || fail "The pod name [${POD_NAME}] doesn't match the pattern for a stateful pod (must end with a number)"
	NODE_ID="${BASH_REMATCH[1]}"
fi
[[ "${NODE_ID}" =~ ^[0-9]+$ ]] || fail "The NODE_ID value [${NODE_ID}] is not a valid number"

# Remove leading zeros
export NODE_ID="$(( 10#${NODE_ID} ))"

# We need to XML-escape this value b/c it will get substituted into text values
KEYSTORE="${SSL_DIR}/keystore.pkcs12"
KEYSTORE_PASSWORD="$(<"${SSL_DIR}/keystore.pass")" || fail "Failed to read the SSL keystore password"

# No need to XML-escape this value, as xmlstarlet will do it for us (also, don't allow empty values)
[ -v ARTEMIS_CLUSTER_PASSWORD ] || ARTEMIS_CLUSTER_PASSWORD=""
[ -n "${ARTEMIS_CLUSTER_PASSWORD}" ] || ARTEMIS_CLUSTER_PASSWORD="PBWaPfidc5Ko8kiof4338RvxZsWwwPOFtDMYF62IXDd5aWGJotw6QH2ARIozKPWE"

# Set the SSL protection for the UI console
cat "${CONF_DIR}/bootstrap.xml.template" | \
	/usr/bin/xmlstarlet ed -P \
		-N "root=http://activemq.apache.org/schema" \
		--update "/root:broker/root:web[@path = 'web']/root:binding/@keyStorePath" -v "${KEYSTORE}" \
		--update "/root:broker/root:web[@path = 'web']/root:binding/@keyStorePassword" -v "${KEYSTORE_PASSWORD}" \
	> "${CONF_DIR}/bootstrap.xml"

# Substitute the hostname where appropriate
/usr/bin/cat "${CONF_DIR}/broker.xml.template" | \
	/usr/bin/xmlstarlet ed -P \
		-N "root=urn:activemq" \
		-N "core=urn:activemq:core" \
		--update "/root:configuration/core:core/core:name" -v "${POD_HOSTNAME}" \
		--update "/root:configuration/core:core/core:cluster-password" -v "${ARTEMIS_CLUSTER_PASSWORD}" \
		--delete "/root:configuration/core:core/core:connectors/core:connector[@name = 'node-${NODE_ID}']" \
		--delete "/root:configuration/core:core/core:cluster-connections/core:cluster-connection/core:static-connectors/core:connector-ref[text() = 'node-${NODE_ID}']" | \
	# For these replacements, the values must first be URL-escaped, then XML-escaped, and finally
	# the & symbol must be escaped so sed doesn't replace it with the matching pattern
	/usr/bin/sed \
		-e "s'\${POD_HOSTNAME}'$(sed_escape "$(xml_escape "$(url_escape "${POD_HOSTNAME}")")")'g" \
		-e "s'\${KEYSTORE}'$(sed_escape "$(xml_escape "$(url_escape "${KEYSTORE}")")")'g" \
		-e "s'\${KEYSTORE_PASSWORD}'$(sed_escape "$(xml_escape "$(url_escape "${KEYSTORE_PASSWORD}")")")'g" \
	> "${CONF_DIR}/broker.xml"

[ -v JAVA_TOOL_OPTIONS ] || JAVA_TOOL_OPTIONS=""

# Require SSL for Zookeeper
JAVA_TOOL_OPTIONS+=" -Dzookeeper.client.secure=true"

CMD="${HOME_DIR}/bin/broker"
[ ${#} -lt 1 ] && set -- "run"
say "Launching: "${CMD@Q}" "${@@Q}""
exec "${CMD}" "${@}"
