apiVersion: v1
kind: Pod
metadata:
  labels:
    app: activemq
  name: activemq
spec:
  containers:
  - env:
    #image: 345280441424.dkr.ecr.ap-south-1.amazonaws.com/ark_activemq:5.17.3
    image: 345280441424.dkr.ecr.ap-south-1.amazonaws.com/ark_activemq:latest
    imagePullPolicy: Always
    #command: ["/bin/sleep", "180d"]
    name: activemq
    ports:
    - containerPort: 8161
      name: console
      protocol: TCP
  hostname: activemq
  imagePullSecrets:
  - name: aws-arkcase-pull
